<a href="https://colab.research.google.com/github/ednavivianasegura/Curso_ML_Python/blob/main/Modulo1_b/02_numpy_1_soluciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell" style="padding:1.5rem 0 2rem;">
  <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:1.5rem;padding-bottom:1.25rem;border-bottom:2px solid #1E3A8A;">
    <div style="flex:1;">
      <span style="display:inline-block;font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#0F766E;background:#CCFBF1;border:1px solid #5EEAD4;padding:3px 10px;border-radius:20px;margin-bottom:8px;">Plan de Formación PDI/PAS 2026</span>
      <div style="font-size:11px;color:#475569;letter-spacing:.6px;text-transform:uppercase;margin-bottom:6px;">Formación para la investigación</div>
      <div style="font-size:11px;font-style:italic;color:#475569;margin-bottom:4px;">Módulo 1 — NumPy · Soluciones</div>
      <h1 style="font-size:24px;font-weight:700;color:#1E3A8A;line-height:1.2;margin:0;">Ejercicios NumPy 1 — Soluciones</h1>
    </div>
    <div style="display:flex;flex-direction:column;align-items:center;gap:6px;flex-shrink:0;">
      <img src="https://github.com/ednavivianasegura/AccesoImages/blob/main/logoUR.png?raw=true" alt="Logo Universidad de La Rioja" style="width:72px;height:auto;">
      <div style="font-size:9px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;text-align:center;line-height:1.4;">Universidad<br>de La Rioja</div>
    </div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px;">
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);">
        <i class="ti ti-list-numbers" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Contenido
      </div>
      <div style="font-size:12.5px;color:#1e293b;line-height:1.7;">16 ejercicios resueltos con explicaciones detalladas y variantes alternativas donde aplica.</div>
    </div>
    <div style="background:#F0FDF4;border:1px solid #99F6E4;border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#0F766E;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid #99F6E4;">
        <i class="ti ti-alert-triangle" style="font-size:13px;color:#0F766E;vertical-align:-1px;"></i> &nbsp;Recomendación
      </div>
      <div style="font-size:12.5px;color:#065F46;line-height:1.7;">Intenta resolver cada ejercicio antes de consultar la solución. El aprendizaje es más efectivo con el intento previo.</div>
    </div>
  </div>
  <div style="display:flex;align-items:center;justify-content:space-between;padding:9px 14px;background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;font-size:11px;color:#94A3B8;">
    <span><i class="ti ti-school" style="font-size:12px;color:#1E3A8A;"></i> Universidad de La Rioja — Logroño, La Rioja</span>
    <span><i class="ti ti-calendar" style="font-size:12px;color:#1E3A8A;"></i> Plan de Formación PDI/PAS 2026</span>
  </div>
</div>

In [2]:
import numpy as np

In [3]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">1</div>
      <div class="ex-title">Vector de números pares</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea un vector con 10 elementos pares.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Puedes usar <code class='ic'>np.arange()</code> con step=2, o list comprehension.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.arange(start, stop, step)</code> genera valores con paso fijo.</span></div>
</div>

In [4]:
# Opción A: arange con step 2
v1 = np.arange(2, 22, 2)
print("Opción A:", v1)

# Opción B: list comprehension
v2 = np.array([i for i in range(1, 100) if i % 2 == 0][:10])
print("Opción B:", v2)

Opción A: [ 2  4  6  8 10 12 14 16 18 20]
Opción B: [ 2  4  6  8 10 12 14 16 18 20]


In [5]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">2</div>
      <div class="ex-title">Dimensiones y tamaño</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén el número de dimensiones y el tamaño del vector del ejercicio 1.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.ndim</code> devuelve el nº de ejes, <code class='ic'>.size</code> el total de elementos, <code class='ic'>.shape</code> la tupla de dimensiones.</span></div>
</div>

In [6]:
print("ndim :", v1.ndim)    # 1  (vector 1D)
print("size :", v1.size)    # 10
print("shape:", v1.shape)   # (10,)

ndim : 1
size : 10
shape: (10,)


In [7]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">3</div>
      <div class="ex-title">Matriz de pares e impares</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea una lista con 5 números pares y otra con 5 impares usando <code class='ic'>list comprehension</code>.</p><p class="ex-task">→ Conviértelas en una matriz de dimensión (5, 2).</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>np.column_stack()</code> para combinar los vectores como columnas.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.column_stack((a, b))</code> apila dos vectores 1D como columnas de una matriz 2D.</span></div>
</div>

In [8]:
pares   = [i for i in range(1, 20) if i % 2 == 0][:5]   # [2, 4, 6, 8, 10]
impares = [i for i in range(1, 20) if i % 2 != 0][:5]   # [1, 3, 5, 7, 9]

# column_stack combina los vectores como columnas → (5, 2)
matriz = np.column_stack((pares, impares))
print(matriz)
print("shape:", matriz.shape)

[[ 2  1]
 [ 4  3]
 [ 6  5]
 [ 8  7]
 [10  9]]
shape: (5, 2)


In [9]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">4</div>
      <div class="ex-title">Tipo de datos</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén el tipo de datos de la matriz del ejercicio 3.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.dtype</code> indica el tipo de cada elemento. Con listas de enteros Python, NumPy infiere <code class='ic'>int64</code>.</span></div>
</div>

In [10]:
print("dtype:", matriz.dtype)   # int64

dtype: int64


In [11]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">5</div>
      <div class="ex-title">Matriz diagonal</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea una matriz de ceros (4, 4) y reemplaza la diagonal principal por 5.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>np.fill_diagonal()</code> o indexado con <code class='ic'>np.arange(4)</code>.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.fill_diagonal(M, val)</code> modifica la diagonal <em>in-place</em>.</span></div>
</div>

In [12]:
M = np.zeros((4, 4), dtype="int")

# Opción A: fill_diagonal (más legible)
np.fill_diagonal(M, 5)
print("Opción A:\n", M)

# Opción B: indexado con array de índices
M2 = np.zeros((4, 4), dtype="int")
idx = np.arange(4)
M2[idx, idx] = 5
print("Opción B:\n", M2)

Opción A:
 [[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]
Opción B:
 [[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


In [13]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">6</div>
      <div class="ex-title">linspace entre -5 y 5</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Usa <code class='ic'>np.linspace()</code> para crear un vector con 10 elementos entre -5 y 5.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.linspace(a, b, n)</code> incluye ambos extremos. El paso es <code class='ic'>(b-a)/(n-1)</code>.</span></div>
</div>

In [14]:
v = np.linspace(-5, 5, 10)
print(v)
# Paso = (5 - (-5)) / (10-1) = 10/9 ≈ 1.111

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [15]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">7</div>
      <div class="ex-title">Matriz vacía flotante</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea una matriz vacía de tamaño (3, 6) con elementos de tipo flotante.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.empty()</code> reserva memoria sin inicializarla. Los valores mostrados son residuos de RAM.</span></div>
</div>

In [16]:
M_empty = np.empty((3, 6), dtype="float64")
print(M_empty)
print("shape:", M_empty.shape)
print("dtype:", M_empty.dtype)

[[3.93375213e-315 0.00000000e+000 1.14448054e+243 4.47593816e-091
  4.47593816e-091 3.29244741e+161]
 [5.39969583e+300 2.75179990e+214 7.10084088e+194 2.83187364e+190
  3.90576582e+233 1.45335791e-308]
 [6.54475997e-310 2.42092166e-322 3.92095572e-315 6.54477488e-310
  6.54475988e-310 6.54475988e-310]]
shape: (3, 6)
dtype: float64


In [17]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">8</div>
      <div class="ex-title">Llenar con números primos</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Rellena la matriz vacía (3×6) con los primeros 18 números primos.</p><p class="ex-task">→ Implementa una función que genere números primos.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">La criba de Eratóstenes es el algoritmo clásico para generar primos eficientemente.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Los primeros 18 primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61.</span></div>
</div>

In [18]:
def primeros_primos(n):
    """Devuelve los primeros n números primos."""
    primos, candidato = [], 2
    while len(primos) < n:
        if all(candidato % p != 0 for p in primos):
            primos.append(candidato)
        candidato += 1
    return primos

# Rellenar la matriz vacía (3x6 = 18 elementos)
M_primos = np.empty((3, 6), dtype="float64")
M_primos[:] = np.array(primeros_primos(18)).reshape(3, 6)
print(M_primos)

[[ 2.  3.  5.  7. 11. 13.]
 [17. 19. 23. 29. 31. 37.]
 [41. 43. 47. 53. 59. 61.]]


In [19]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">9</div>
      <div class="ex-title">Slicing con imagen de referencia</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Reemplaza los números dentro del círculo por 99 usando slicing.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">El círculo rodea los elementos centrales. Usa <code class='ic'>matriz[fila_ini:fila_fin, col_ini:col_fin] = 99</code>.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El círculo rodea la submatriz filas 1–3, columnas 1–3. El slicing <code class='ic'>[1:4, 1:4]</code> selecciona esa región.</span></div>
</div>

In [20]:
# @title
%%html

<div style="text-align:center;margin:8px 0 14px;">
  <img src="https://github.com/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/Imagenes%20Notebooks/numpy_1.png?raw=true"
       alt="Matriz con círculo" style="width:50%;max-width:400px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,.1);">
</div>

In [21]:
matriz = np.array([[ 1,  2,  3,  4,  5],
                   [ 6,  7,  8,  9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])
print("Original:\n", matriz)

# El círculo rodea la submatriz central: filas 1:4, columnas 1:4
matriz[1:4, 1:4] = 99
print("\nCon 99s:\n", matriz)

Original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Con 99s:
 [[ 1  2  3  4  5]
 [ 6 99 99 99 10]
 [11 99 99 99 15]
 [16 99 99 99 20]
 [21 22 23 24 25]]


In [22]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">10</div>
      <div class="ex-title">Primera y tercera fila</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén la primera y tercera fila de la matriz del ejercicio 9.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Para filas no contiguas usa <em>fancy indexing</em>: <code class='ic'>matriz[[0, 2]]</code>.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Índices desde 0: primera fila = 0, tercera fila = 2.</span></div>
</div>

In [23]:
# Fancy indexing: primera fila = índice 0, tercera = índice 2
print(matriz[[0, 2]])

# Alternativa con slicing (paso 2)
print(matriz[0:3:2])

[[ 1  2  3  4  5]
 [11 99 99 99 15]]
[[ 1  2  3  4  5]
 [11 99 99 99 15]]


In [24]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">11</div>
      <div class="ex-title">Tercera columna</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén la tercera columna de la matriz.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>matriz[:, idx]</code> — el <code class='ic'>:</code> significa 'todas las filas'.</span></div>
</div>

In [25]:
# : en filas = todas las filas; 2 = tercera columna (índice 2)
print(matriz[:, 2])

[ 3 99 99 99 23]


In [26]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">12</div>
      <div class="ex-title">Segunda y tercera columna</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén la segunda y tercera columna de la matriz.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>matriz[:, 1:3]</code> selecciona columnas con índice 1 y 2 (el 3 no se incluye).</span></div>
</div>

In [27]:
# Slicing de columnas: 1:3 selecciona índices 1 y 2
print(matriz[:, 1:3])

[[ 2  3]
 [99 99]
 [99 99]
 [99 99]
 [22 23]]


In [28]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">13</div>
      <div class="ex-title">Submatriz central</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén una submatriz con los 4 números del centro de la matriz.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Para una matriz 5×5 los 4 elementos del centro están en filas 1–2 y columnas 1–2.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El resultado debe tener <code class='ic'>shape (2, 2)</code>.</span></div>
</div>

In [29]:
# Submatriz 2x2 central (filas 1-2, columnas 1-2)
centro = matriz[1:3, 1:3]
print(centro)
print("shape:", centro.shape)   # (2, 2)

[[99 99]
 [99 99]]
shape: (2, 2)


In [30]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">14</div>
      <div class="ex-title">flatten</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Aplica <code class='ic'>.flatten()</code> a la submatriz anterior.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.flatten()</code> devuelve una <strong>copia</strong> 1D. A diferencia de <code class='ic'>.ravel()</code>, los cambios no afectan al original.</span></div>
</div>

In [31]:
# flatten devuelve una COPIA 1D (no modifica el original)
vector = centro.flatten()
print(vector)
print("shape:", vector.shape)   # (4,)

[99 99 99 99]
shape: (4,)


In [32]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">15</div>
      <div class="ex-title">reshape a (1, 4)</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Aplica <code class='ic'>.reshape()</code> al vector para obtener una matriz de dimensión (1, 4).</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>(4,)</code> es 1D; <code class='ic'>(1, 4)</code> es 2D. Visualmente similar pero <code class='ic'>.ndim</code> cambia de 1 a 2.</span></div>
</div>

In [33]:
mat_1x4 = vector.reshape(1, 4)
print(mat_1x4)
print("shape:", mat_1x4.shape)   # (1, 4)
print("ndim :", mat_1x4.ndim)    # 2  (ahora es 2D)

[[99 99 99 99]]
shape: (1, 4)
ndim : 2


In [34]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">16</div>
      <div class="ex-title">Concatenación vertical</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea dos matrices (4, 4) con números aleatorios y concaténalas verticalmente.</p>
    </div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>np.concatenate(..., axis=0)</code> o el alias <code class='ic'>np.vstack()</code>.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.vstack((A, B))</code> es equivalente a <code class='ic'>np.concatenate((A, B), axis=0)</code>. Resultado: forma (8, 4).</span></div>
</div>

In [35]:
np.random.seed(42)   # semilla para reproducibilidad
A = np.random.randint(1, 10, size=(4, 4))
B = np.random.randint(1, 10, size=(4, 4))
print("A:\n", A)
print("B:\n", B)

# Opción A: concatenate con axis=0
resultado = np.concatenate((A, B), axis=0)
print("\nconcatenate axis=0 (8x4):\n", resultado)

# Opción B: vstack (equivalente)
resultado2 = np.vstack((A, B))
print("\nvstack (8x4):\n", resultado2)
print("shape:", resultado.shape)

A:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
B:
 [[8 6 2 5]
 [1 6 9 1]
 [3 7 4 9]
 [3 5 3 7]]

concatenate axis=0 (8x4):
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]
 [8 6 2 5]
 [1 6 9 1]
 [3 7 4 9]
 [3 5 3 7]]

vstack (8x4):
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]
 [8 6 2 5]
 [1 6 9 1]
 [3 7 4 9]
 [3 5 3 7]]
shape: (8, 4)
